# Generated by Django 3.0.6 on 2020-12-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='univ_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='大学名'),
        ),
    ]
