# Generated by Django 3.0.6 on 2020-11-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201117_1524'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Skill',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='tag_id',
            new_name='skill_id',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='tag_name',
            new_name='skill_name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='prof_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/', verbose_name='プロフィール画像'),
        ),
    ]
