# Generated by Django 3.0.6 on 2020-12-13 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        ('user', '0003_auto_20201212_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ストックID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event', verbose_name='ユーザーが保存したイベント')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='保存したユーザー')),
            ],
        ),
    ]
