# Generated by Django 3.0.6 on 2020-11-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201125_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_level',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='持っているスキルのレベル'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='prof_img',
            field=models.ImageField(blank=True, null=True, upload_to='user/', verbose_name='プロフィール画像'),
        ),
    ]
