# Generated by Django 3.0.6 on 2020-11-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201125_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='連絡先(SNSアカウント等)'),
        ),
    ]
