# Generated by Django 3.0.6 on 2020-11-25 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201125_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='contact',
        ),
    ]
