# Generated by Django 3.0.6 on 2020-12-14 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaTagMap',
            fields=[
                ('ideatag_id', models.AutoField(primary_key=True, serialize=False, verbose_name='アイデアタグのID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False, verbose_name='タグID')),
                ('tag_name', models.CharField(max_length=20, verbose_name='タグ名')),
            ],
        ),
        migrations.CreateModel(
            name='UserTagMap',
            fields=[
                ('usertag_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ユーザータグのID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.Tag')),
            ],
        ),
    ]
