# Generated by Django 3.0.6 on 2020-12-14 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idea', '0002_auto_20201214_1103'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertagmap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ideatagmap',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea.PostIdea'),
        ),
        migrations.AddField(
            model_name='ideatagmap',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.Tag'),
        ),
    ]
