# Generated by Django 3.0.6 on 2020-12-15 05:24


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostIdea',
            fields=[
                ('idea_id', models.AutoField(primary_key=True, serialize=False, verbose_name='アイデアID')),
                ('title', models.CharField(default='Idea Title', max_length=100, verbose_name='タイトル')),
                ('overview', models.TextField(blank=True, max_length=500, null=True, verbose_name='概要')),
                ('background', models.TextField(blank=True, max_length=500, null=True, verbose_name='背景')),
                ('passion', models.TextField(blank=True, max_length=500, null=True, verbose_name='思い')),
                ('idea_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='投稿画像')),
                ('idea_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日')),
                ('state', models.CharField(max_length=100, verbose_name='状態')),
                ('target', models.CharField(max_length=100, verbose_name='ターゲット')),
                ('offer', models.CharField(max_length=100, verbose_name='人材募集')),
                ('deadline', models.CharField(max_length=30, verbose_name='期日')),
                ('uniqueness', models.IntegerField(default=0, verbose_name='ユニークさ')),
                ('novelty', models.IntegerField(default=0, verbose_name='新規性')),
                ('possibility', models.IntegerField(default=0, verbose_name='実現可能性')),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.Event', verbose_name='イベント')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='アイデア投稿ユーザ')),
            ],
            options={
                'db_table': 'Post_Idea',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='コメントID')),
                ('comment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='コメント投稿日')),
                ('comment', models.TextField(max_length=255, verbose_name='コメント')),
                ('idea_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea.PostIdea', verbose_name='アイデアID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='コメントユーザ')),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
    ]
