<<<<<<< Updated upstream
# Generated by Django 3.0.6 on 2020-12-19 05:45
=======
# Generated by Django 3.0.6 on 2020-12-19 05:31
>>>>>>> Stashed changes

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< Updated upstream
=======
        ('event', '0001_initial'),
>>>>>>> Stashed changes
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='コメントID')),
                ('comment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='コメント投稿日')),
                ('comment', models.TextField(max_length=255, verbose_name='コメント')),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='PostIdea',
            fields=[
                ('idea_id', models.AutoField(primary_key=True, serialize=False, verbose_name='アイデアID')),
                ('title', models.CharField(default='Idea Title', max_length=100, verbose_name='タイトル')),
                ('overview', models.TextField(blank=True, max_length=500, null=True, verbose_name='概要')),
                ('background', models.TextField(blank=True, max_length=500, null=True, verbose_name='背景')),
                ('passion', models.TextField(blank=True, max_length=500, null=True, verbose_name='思い')),
                ('idea_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='投稿画像')),
                ('idea_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日')),
                ('state', models.CharField(max_length=100, verbose_name='状態')),
                ('target', models.CharField(blank=True, max_length=100, null=True, verbose_name='ターゲット')),
                ('offer', models.CharField(blank=True, max_length=100, null=True, verbose_name='人材募集')),
                ('deadline', models.CharField(blank=True, max_length=30, null=True, verbose_name='期日')),
                ('interesting', models.IntegerField(blank=True, default=0, null=True, verbose_name='面白さ')),
                ('novelty', models.IntegerField(blank=True, default=0, null=True, verbose_name='新規性')),
                ('possibility', models.IntegerField(blank=True, default=0, null=True, verbose_name='実現可能性')),
<<<<<<< Updated upstream
=======
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.Event', verbose_name='イベント')),
>>>>>>> Stashed changes
            ],
            options={
                'db_table': 'Post_Idea',
            },
        ),
<<<<<<< Updated upstream
        migrations.CreateModel(
            name='ReputationMap',
            fields=[
                ('reputation_id', models.AutoField(primary_key=True, serialize=False, verbose_name='reputationのID')),
                ('name', models.TextField(max_length=255, verbose_name='反応')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea.PostIdea', verbose_name='反応先のアイデア')),
            ],
        ),
=======
>>>>>>> Stashed changes
    ]
