# Generated by Django 3.0.6 on 2020-12-02 01:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requiredskill',
            name='skill_level',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='スキルレベル'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='コメント日時'),
        ),
        migrations.AlterField(
            model_name='postidea',
            name='idea_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日時'),
        ),
    ]
