# Generated by Django 3.0.6 on 2021-01-07 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0001_initial'),
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reputationmap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='反応したユーザー'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea.PostIdea', verbose_name='募集中のアイデア'),
        ),
        migrations.AddField(
            model_name='postidea',
            name='event_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.Event', verbose_name='イベント'),
        ),
        migrations.AddField(
            model_name='postidea',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='アイデア投稿ユーザ'),
        ),
        migrations.AddField(
            model_name='feedbackquestion',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea.PostIdea', verbose_name='feedback先のアイデア'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea.FeedbackQuestion', verbose_name='投稿者の質問'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='フィードバックユーザ'),
        ),
    ]
