# Generated by Django 3.1.2 on 2020-11-11 01:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postidea',
            name='idea_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 11, 1, 25, 56, 424786, tzinfo=utc), verbose_name='投稿日時'),
        ),
        migrations.AlterField(
            model_name='postidea',
            name='idea_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='投稿画像'),
        ),
        migrations.AlterField(
            model_name='postidea',
            name='idea_movie',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='投稿動画ファイル'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 11, 1, 25, 56, 426068, tzinfo=utc), verbose_name='リプライ日時'),
        ),
    ]
