# Generated by Django 3.0.6 on 2020-12-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_auto_20201214_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postidea',
            name='overview',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='概要'),
        ),
    ]
