# Generated by Django 3.0.6 on 2020-12-16 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_auto_20201216_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='コメント投稿日'),
        ),
        migrations.AlterField(
            model_name='postidea',
            name='idea_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日'),
        ),
    ]
