# Generated by Django 3.0.6 on 2020-12-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0003_auto_20201216_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postidea',
            name='uniqueness',
        ),
        migrations.AddField(
            model_name='postidea',
            name='interesting',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='面白さ'),
        ),
    ]
